name: Release npm package

on:
  push:
    branches:
      - master
      - release-process-jant

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: 'node:lts'
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm test
      - run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
